name: Task
description: A tracked unit of work
title: "task: "
labels: ["task"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance criteria
      value: |
        - [ ]
        - [ ]
    validations:
      required: true
